### ISSUE TITLE
feat/backend: add character from contract

### ISSUE THREAD

**Issue by leeduckgo** [WeLightProject/tai_shang_world_generator#52]
悬赏金额：`¥200`
从合约加载角色，TODO File：
> https://github.com/WeLightProject/tai_shang_world_generator/blob/main/lib/tai_shang_world_generator/nft/character_loader.ex

**Comment by yangcancai** [comment]
除了elixir需要了解别的知识吗？我看看可不可以接

**Comment by leeduckgo** [comment]
> 除了elixir需要了解别的知识吗？我看看可不可以接

再搭配点区块链知识，但只要移植：

> https://github.com/WeLightProject/tai_shang_nft_gallery/tree/main/lib/tai_shang_nft_gallery/nft

这里的 `interactor` 和 `parser` 就能实现。

**Comment by leeduckgo** [comment]
> 除了elixir需要了解别的知识吗？我看看可不可以接

加微信哦：197626581

**Comment by yangcancai** [comment]
> > 除了elixir需要了解别的知识吗？我看看可不可以接
> 
> 加微信哦：197626581

加了

**Comment by yangcancai** [comment]
我接了

**Comment by leeduckgo** [comment]
Done
