### ISSUE TITLE
前端重构工作

### ISSUE THREAD

**Issue by leeduckgo** [WeLightProject/tai_shang_world_generator#75]
悬赏金额：`¥1000`

要求：

- [x] 使用 React 框架 `¥600`: [重构所在分支](https://github.com/WeLightProject/tai_shang_world_generator/tree/refactor-react)
- [x] 集成 Web3 登录方式 `¥200`
- [ ] 实现对后端传过来的值用 Metamask 签名的方法，并发送签名后的值到前端进行验证 `¥200`
> https://github.com/spruceid/siwe/

**Comment by qiwihui** [comment]
我认领以下两个任务：
- 集成 Web3 登录方式
- 实现对后端传过来的值用 Metamask 签名的方法，并发送签名后的值到前端进行验证

**Comment by qiwihui** [comment]
重构前端我也认领了 🤣

**Comment by leeduckgo** [comment]
> 重构前端我也认领了 🤣

Great!

**Comment by qiwihui** [comment]
update:
目前进度：重构部分页面组件结构基本完成，正在添加操作功能。

**Comment by leeduckgo** [comment]
The first one Done.

**Comment by leeduckgo** [comment]
Congratulate for finish!
